# Generated by Django 5.0.6 on 2024-06-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='App.q'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
